Fix to build basel-face-model-viewer #15
unibas-gravis/basel-face-model-viewer pull request #16
Opened 2021-05-04 16:01 UTC by wolfviking0

Update the scala version to 2.13.0
Update the scalismo-faces version to 0.90.0
Fix 2.13 warning

Signed-off-by: wolfviking0 <wolfviking0@yahoo.com>

2021-05-04 16:03 UTC, wolfviking0 commented
Hi @Andreas-Forster,

I  was able to build the Basel-face-model-viewer. I also remove the warning related to 2.13.0 but its my first time in Scala so please review carefully the little change are not breaking anything :)

2021-05-05 07:56 UTC, Andreas-Forster requested changes
Thank you a lot for the update and fixes you did. I have only a few minor comments.

I was unsure if I should update the PR by pushing to your master branch. If you use a different/feature branch next time I will try to make the changes directly by pushing to your branch.

For improved code clarity, I would suggest that we use the new default immutable Seq in the getModelFile function. Further comments are dealing with some warnings of the IDE (IntelliJ).

2021-05-05 07:56 UTC, Andreas-Forster commented on src/main/scala/faces/apps/ModelViewer.scala
> + import collection.{ Seq => CSeq }
Could you please remove this line,
change line 45 back to using the type Seq,
and  add `.toIndexedSeq` to the variable `args `where `getModelFile` is called?

I think its totally fine if there is now an immutable Seq used in `getModelFile`.

2021-05-05 07:56 UTC, Andreas-Forster commented on src/main/scala/faces/apps/ModelViewer.scala
> +  private def getModelFile(args: CSeq[String]): Option[File] = {
Please revert changes here. See the comment above at the import statement.

2021-05-05 07:56 UTC, Andreas-Forster commented on src/main/scala/faces/apps/ModelViewer.scala
> +      if ( !file.getName.endsWith(".ply")) file = new File( file.getAbsolutePath()+".ply")
Could you please remove the empty parenthesis? This will fix a warning in the IDE (intellij).

2021-05-05 07:56 UTC, Andreas-Forster commented on src/main/scala/faces/apps/ModelViewer.scala
> +      if ( !file.getName.endsWith(".png")) file = new File( file.getAbsolutePath()+".png")
Could you please remove the empty parenthesis? This will fix a warning in the IDE (intellij).

2021-05-05 16:12 UTC, wolfviking0 commented
Hi @Andreas-Forster  I fixed the PR base on your suggestion. IntelliJ was giving me few other warning regarding one type error :  expressio instead of expression and some generic type. So I just follow the suggestion of IntelliJ to remove those warning. Let me know what you think about it .

2021-05-06 06:27 UTC, Andreas-Forster approved these changes
Awesome work. Thank you very much, also for fixing the typos we introduced earlier.

2021-05-06 06:29 UTC, merged